-- ============================================================================
-- Phase 2 — Role tier enforcement at the RLS layer.
--
-- After Phase 1 added the `supervisor` enum value and the is_supervisor()
-- helper (20260528110000 / 20260528110100), several write policies still
-- allowed ANY company_member to mutate rows that should require a higher
-- trust tier. Phase 2 tightens those policies.
--
-- Scope of THIS migration:
--   * ai_replies UPDATE  — was company-scoped (any member could
--     approve/edit/reject any draft). Tightened to supervisor-or-above,
--     still scoped to the user's own company conversations. The READ
--     (SELECT) policy stays company-scoped on purpose: agents need to
--     SEE the AI drafts attached to their conversations; they just
--     cannot mutate them. INSERT also stays company-scoped because
--     drafts are generated by the AI pipeline (server-side, often via
--     the user's session) — gating INSERT here would block normal
--     draft creation.
--
-- Verified untouched (already correctly scoped — no change needed):
--   * contacts UPDATE/DELETE — already is_company_admin() per
--     20260501170000_tighten_rls_company_scoping.sql. Confirmed in
--     pg_policy before writing this migration.
--   * conversations UPDATE — intentionally left company-scoped. RLS
--     cannot column-gate (merged_into_id / assigned_to). The API
--     layer enforces supervisor-only on merge/assign endpoints; RLS
--     remains a coarse company-isolation boundary.
--
-- Invariants preserved in every new policy:
--   * super_admin bypass: every clause starts with `is_super_admin() OR ...`
--   * tenant isolation: writes are still gated to the caller's own
--     company via accounts.company_id = current_user_company_id().
-- ============================================================================

-- --- ai_replies UPDATE -------------------------------------------------------
-- Drop the old company-scoped UPDATE policy and replace with a
-- supervisor-gated, company-scoped version. Same shape for USING and
-- WITH CHECK so a row can't be moved out of the caller's tenant.

DROP POLICY IF EXISTS "Users update own company ai_replies" ON public.ai_replies;

CREATE POLICY "Supervisors update own company ai_replies"
  ON public.ai_replies
  FOR UPDATE
  USING (
    is_super_admin()
    OR (
      is_supervisor()
      AND conversation_id IN (
        SELECT id FROM public.conversations
        WHERE account_id IN (
          SELECT id FROM public.accounts
          WHERE company_id = current_user_company_id()
        )
      )
    )
  )
  WITH CHECK (
    is_super_admin()
    OR (
      is_supervisor()
      AND conversation_id IN (
        SELECT id FROM public.conversations
        WHERE account_id IN (
          SELECT id FROM public.accounts
          WHERE company_id = current_user_company_id()
        )
      )
    )
  );
